<?xml version="1.0" encoding="UTF-8"?>
<AddressValidateResponse>
    <Address ID="0">
        <FirmName>SLALOM</FirmName>
        <Address1>STE 300</Address1>
        <Address2>316 STUART ST</Address2>
        <City>BOSTON</City>
        <State>MA</State>
        <Zip5>02116</Zip5>
        <Zip4>5242</Zip4>
        <DeliveryPoint>16</DeliveryPoint>
        <CarrierRoute>C027</CarrierRoute>
    </Address>
</AddressValidateResponse>